#!/bin/sh

. ~/.config/bspwm/bspwm-rules
. ~/.config/bspwm/bspwm-config

# variables
terminal="alacritty"
editor="nvim"
# monitor1=$(xrandr | grep "primary" | awk '{print $1}')
# monitor2=$(xrandr | grep -w "connected" | awk '{i++}i==2' | awk '{print $1}')
monitor1="DP-4"
monitor2="HDMI-0"

# auto exec
pgrep -x sxhkd > /dev/null || sxhkd &
killall -9 dunst; pgrep -x dunst > /dev/null || dunst &
pgrep -x solaar > /dev/null || solaar -w hide &
feh --bg-fill ~/wlp.png &
nm-applet &
picom &
${HOME}/scripts/polybar.sh &
${HOME}/scripts/monitors.sh &
xsetroot -cursor_name left_ptr
xset s off -dpms
setxkbmap fi
xrdb ~/.Xresources

pgrep -x Discord > /dev/null || discord &
# pgrep -x obs > /dev/null || obs &

# desktops
if [[ $HOSTNAME == "sharkcat" ]]; then
 	bspc monitor $monitor1 -d 4 5 6 7 8 9 10
	bspc monitor $monitor2 -d 1 2 3
    # bspc monitor -d 1 2 3 4 5 6 7
elif [[ $HOSTNAME == "catshark" ]]; then
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi