#!/bin/sh


bspc config ignore_ewmh_focus        true

bspc config border_width             2
bspc config window_gap               10
bspc config top_padding 		     0
bspc config bottom_padding 		     0

bspc config split_ratio              0.50
bspc config borderless_monocle       false
bspc config gapless_monocle          false
bspc config single_monocle			 false
bspc config top_monocle_padding      0
bspc config bottom_monocle_padding   0
bspc config presel_feedback			 false

bspc config pointer_action1			 move
bspc config pointer_action2			 resize_side
bspc config pointer_action2			 resize_corner
bspc config focus_follows_pointer    true
#bspc config pointer_follows_monitor  true

bspc config normal_border_color     \#363636
bspc config active_border_color     \#363636
bspc config focused_border_color    \#999999
bspc config presel_feedback_color   \#ffffff
